"""add_ticker_and_sector_to_stock_holdings_table

Revision ID: e60e0ddcae26
Revises: 
Create Date: 2025-06-04 23:58:57.541917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60e0ddcae26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_holdings', sa.Column('ticker', sa.String(), nullable=True))
    op.create_index(op.f('ix_stock_holdings_ticker'), 'stock_holdings', ['ticker'], unique=False)
    op.add_column('stock_holdings', sa.Column('sector', sa.String(), nullable=True, server_default='Others'))
    op.create_index(op.f('ix_stock_holdings_sector'), 'stock_holdings', ['sector'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_holdings_sector'), table_name='stock_holdings')
    op.drop_column('stock_holdings', 'sector')
    op.drop_index(op.f('ix_stock_holdings_ticker'), table_name='stock_holdings')
    op.drop_column('stock_holdings', 'ticker')
    # ### end Alembic commands ###
